/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, System as PrismaSystem } from "@prisma/client";

export class SystemServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.SystemCountArgs, "select">): Promise<number> {
    return this.prisma.system.count(args);
  }

  async systems(args: Prisma.SystemFindManyArgs): Promise<PrismaSystem[]> {
    return this.prisma.system.findMany(args);
  }
  async system(
    args: Prisma.SystemFindUniqueArgs
  ): Promise<PrismaSystem | null> {
    return this.prisma.system.findUnique(args);
  }
  async createSystem(args: Prisma.SystemCreateArgs): Promise<PrismaSystem> {
    return this.prisma.system.create(args);
  }
  async updateSystem(args: Prisma.SystemUpdateArgs): Promise<PrismaSystem> {
    return this.prisma.system.update(args);
  }
  async deleteSystem(args: Prisma.SystemDeleteArgs): Promise<PrismaSystem> {
    return this.prisma.system.delete(args);
  }
}
