/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ShopService } from "../shop.service";
import { ShopCreateInput } from "./ShopCreateInput";
import { Shop } from "./Shop";
import { ShopFindManyArgs } from "./ShopFindManyArgs";
import { ShopWhereUniqueInput } from "./ShopWhereUniqueInput";
import { ShopUpdateInput } from "./ShopUpdateInput";

export class ShopControllerBase {
  constructor(protected readonly service: ShopService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Shop })
  async createShop(@common.Body() data: ShopCreateInput): Promise<Shop> {
    return await this.service.createShop({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Shop] })
  @ApiNestedQuery(ShopFindManyArgs)
  async shops(@common.Req() request: Request): Promise<Shop[]> {
    const args = plainToClass(ShopFindManyArgs, request.query);
    return this.service.shops({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Shop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async shop(
    @common.Param() params: ShopWhereUniqueInput
  ): Promise<Shop | null> {
    const result = await this.service.shop({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Shop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateShop(
    @common.Param() params: ShopWhereUniqueInput,
    @common.Body() data: ShopUpdateInput
  ): Promise<Shop | null> {
    try {
      return await this.service.updateShop({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Shop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteShop(
    @common.Param() params: ShopWhereUniqueInput
  ): Promise<Shop | null> {
    try {
      return await this.service.deleteShop({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
